CREATE TABLE TRADES (
    ID VARCHAR(36) PRIMARY KEY,
    SYMBOL VARCHAR(10) NOT NULL,
    QUANTITY DECIMAL(10, 2) NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    EXCHANGE VARCHAR(10) NOT NULL,
    TIMESTAMP TIMEStAMP NOT NULL
);